[package]
name = "staking_rewards"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban_pausable_core = { path = "../soroban_pausable_core" }
soroban-sdk = "22"
soroban_storage_ttl = { path = "../soroban_storage_ttl" }

[dev-dependencies]
soroban-sdk = { version = "22", features = ["testutils"] }

